module.exports = {
  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_TERMS: 'PROJECT_TERMS',
  PROJECT_CLEAN: 'PROJECT_CLEAN',
  CONTRIBUTORS: 'CONTRIBUTORS',
  CONTRIBUTORS_LIST: 'CONTRIBUTORS_LIST',
  CONTRIBUTORS_ADD: 'CONTRIBUTORS_ADD',
  CONTRIBUTORS_DELETE: 'CONTRIBUTORS_DELETE',
}
